name: RCF weekly podiums

on:
  schedule:
    - cron: "0 18 * * 0"   # sunnuntai 18:00 UTC (~21:00 EET/EEST)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rcf-discord-news

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Weekly podiums
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          ZWIFTPOWER_COOKIE: ${{ secrets.ZWIFTPOWER_COOKIE }}
          ZWIFTPOWER_TEAM_ID: "20561"
          DEBUG: "1"
        run: |
          python weekly_podiums.py

      - name: Commit weekly_seen.json if changed
        run: |
          if [[ -n "$(git status --porcelain weekly_seen.json)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add weekly_seen.json
            git commit -m "chore: update weekly_seen.json [skip ci]" || true
            git push
          else
            echo "No changes to commit"
          fi
