name: RCF Weekly Podiums

on:
  schedule:
    - cron: "0 17 * * 0"   # Sunnuntai klo 20 Suomen aikaa (17 UTC)
  workflow_dispatch:       # Manuaalinen ajo GitHubista

jobs:
  weekly:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rcf-discord-news

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run podium bot
        env:
          ZWIFTPOWER_COOKIE: ${{ secrets.ZWIFTPOWER_COOKIE }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          ZWIFTPOWER_TEAM_ID: "20561"   # vaihda jos testaat eri tiimillä
          DEBUG: "1"                    # tallettaa last_team_page.html
          ALWAYS_POST: "1"              # pakottaa viestin testissä
        run: python weekly_podiums.py

      - name: Show HTML head and tail
        if: always()
        run: |
          echo "----- HEAD OF HTML -----"
          head -n 80 last_team_page.html || true
          echo "----- TAIL OF HTML -----"
          tail -n 80 last_team_page.html || true

      - name: Upload debug HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: last_team_page
          path: last_team_page.html
          if-no-files-found: ignore
