name: RCF Weekly Podiums

on:
  schedule:
    # Sunnuntai klo 20:00 Suomen aikaa = 17:00 UTC
    - cron: "0 17 * * 0"
  workflow_dispatch: {}   # Manuaalinen ajo

jobs:
  weekly:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rcf-discord-news

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run podium bot
        env:
          # ZwiftPowerin istuntocookie ja Discord-webhook talletetaan secreteinä
          ZWIFTPOWER_COOKIE: ${{ secrets.ZWIFTPOWER_COOKIE }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          # Vaihda tarvittaessa testiin eri tiimi
          ZWIFTPOWER_TEAM_ID: "20561"
          # Debug päälle -> tallentaa last_team_page.html
          DEBUG: "1"
          # Testissä voit asettaa 0 jos et halua väkisin postausta
          ALWAYS_POST: "1"
        run: python weekly_podiums.py

      - name: Show HTML head and tail
        if: always()
        run: |
          echo "----- HEAD OF HTML -----"
          head -n 80 rcf-discord-news/last_team_page.html || true
          echo "----- TAIL OF HTML -----"
          tail -n 80 rcf-discord-news/last_team_page.html || true

      - name: Upload debug HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: last_team_page
          path: rcf-discord-news/last_team_page.html
          if-no-files-found: ignore
